---
name: product_demos
topology:
  kinds:
    cisco_c8000v:
      image: registry.gitlab.com/redhatautomation/cat8:17.13.01a
    cisco_n9kv:
      image: registry.gitlab.com/redhatautomation/nexus10-ee:10.5.3.F
  nodes:
    n9kv:
      kind: cisco_n9kv
      startup-config: configs/n9kv/startup-config.cfg
      ports:
        - "2122:22"
    cat8kv:
      kind: cisco_c8000v
      startup-config: configs/cat8kv/startup-config.cfg
      ports:
        - "2123:22"
    scp-server:      
      kind: linux
      image: python:3.11-slim
      mgmt-ipv4: 172.20.20.11
      exec:
        - bash -c "apt-get update && apt-get install -y openssh-server"
        - mkdir -p /run/sshd
        - useradd -m -s /bin/bash scpuser
        - bash -c "echo 'scpuser:scpuser' | chpasswd"
        - /usr/sbin/sshd
        - pip install gdown
        - gdown "https://drive.google.com/uc?id=1cPPO1mxIZf4weIi497r3ffGC5g0_S58i" -O /home/scpuser/c8000v-universalk9.17.15.01a.SPA.bin
        - chown scpuser:scpuser /home/scpuser/c8000v-universalk9.17.15.01a.SPA.bin