---
- name: Playbook to upgrade router 
  hosts: cisco
  gather_facts: False
 
  tasks:

  - name: Change boot system to load new image next reload
    cisco.ios.ios_config:
      lines: 
       - "boot system bootflash:packages.conf"
      before:
       - 'no boot system'
      save_when: always

  - name: Check if correct image still exist in bootflash, if not FAIL the playbook
    cisco.ios.ios_command:
      commands: 'dir bootflash: | include {{ new_image_ios }}'
    register: check_image
    failed_when: check_image.stdout[0].find( new_image_ios )  == -1
 
  - name: Please wait for Install mode to complete the IOS upgrade
    ansible.builtin.debug:
      msg: "Please wait for Install mode to complete the IOS upgrade to version: {{ new_image_ios }}..."
  
  - name: Install new version with activate and commit
    vars:
      ansible_command_timeout: 1200
    cisco.ios.ios_command:
      commands: 
        - command: install add file bootflash:{{ new_image_ios }} activate commit
          prompt: 
          - 'This operation may require a reload of the system. Do you want to proceed\? \[y/n]'
          answer: 
          - 'y'
    register: install_activate_output
   
  - name: Display install activate output
    ansible.builtin.debug:
      var: install_activate_output.stdout_lines

  - name: Please wait for the router to reboot
    ansible.builtin.debug:
      msg: "Please wait for {{ inventory_hostname }} to reboot..."
    when: "'No Change' not in install_activate_output.stdout[0]"

  - name: Wait for SSH port to come back
    wait_for:
      host: "{{ ansible_host }}"
      port: "{{ ansible_port }}"
      delay: 60
      timeout: 550
    connection: local
    when: "'No Change' not in install_activate_output.stdout[0]"

  - name: Wait for IOS-XE to be fully ready
    cisco.ios.ios_command:
      commands: show version
    register: post_reboot_version
    retries: 10
    delay: 30
    until: post_reboot_version is not failed
    when: "'No Change' not in install_activate_output.stdout[0]"
    
- name: Playbook to confirm bootloader after reload
  hosts: cisco
  gather_facts: False
  vars:
   new_version: "{{ image_upgrade }}" 
   new_image_ios: "c8000v-universalk9.{{ new_version }}.SPA.bin" 

  tasks:

  - name: show bootloader config
    cisco.ios.ios_command:
      commands: 'sh version'
    register: version2

  - name: assert bootloader config changed
    ansible.builtin.assert:
      that: 
        - "new_version in version2['stdout'][0]"
      fail_msg: "{{new_version}} is not present"
      success_msg: "{{new_version}} is present"
